name = "themorphstudios"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "the_morphstudios_db"
database_name = "the-morphstudios-db"
database_id = "719d9b51-1cc4-413d-ace0-f62ca6312e69"