name = "morph-studio"
compatibility_date = "2024-03-20"
pages_build_output_dir = ".vercel/output/static"

# This enables native Node.js features like Web Crypto on the Edge
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "morph-db"
# We will generate this ID in the Cloudflare Dashboard in the next step
database_id = "f16a276f-a854-43f8-a7ad-e1eb875f3dc6"